# Generated by Django 5.2.1 on 2025-06-01 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0002_alter_user_managers_user_groups_user_is_superuser_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
